### ISSUE TITLE
characters is deprecated

### ISSUE THREAD

**Issue by maledettobue** [DigitalLeaves/CommonCrypto-in-Swift#2]
Hi, I wanted to try your wrapper when I found a warning for this line:

private let kSymmetricCryptorRandomStringGeneratorCharset: [Character] = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789".characters.map({$0})

'characters' is deprecated: Please use String or Substring directly. How can I edit the code to update it?

I'm using XCode 9.1 / Swift 3.2

Thanks in advance

**Comment by DigitalLeaves** [comment]
Hi there. Sure, just remove the .characters


             <https://digitalleaves.com/>          

Ignacio Nieto Carvajal  / senior freelance developer  
contact@digitalleaves.com <mailto:contact@digitalleaves.com>
Digital Leaves  
https://digitalleaves.com <https://digitalleaves.com/>
   <https://twitter.com/digitalleaves>     <https://www.facebook.com/DigitalLeaves/>     <https://es.linkedin.com/in/digitalleaves>     <https://github.com/DigitalLeaves>

**Comment by maledettobue** [comment]
Oh, I really misunderstood the sense of the warning: I thought the replacement was a method of String or Substring, not the complete removal of "characters"   :-)   Thanks!
